name: Deploy to Netlify

on:
  check_suite:
    types: [completed]
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref : ${{ github.ref || github.head_ref || github.ref_name }}

      - name: Cache pnpm modules and build
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            build/taro-docs
          key: ${{ runner.os }}-preview
          restore-keys: |
            ${{ runner.os }}-

      - name: install
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm run build:zone

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.0.12
        with:
          publish-dir: "./dist"
          production-branch: docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      # - uses: amondnet/now-deployment@v2
      #   timeout-minutes: 10
      #   with:
      #     zeit-token: ${{ secrets.ZEIT_TOKEN }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     now-org-id: ${{ secrets.ORG_ID}}
      #     now-project-id: ${{ secrets.PROJECT_ID}}
