name: Node CI

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref : ${{ github.ref || github.head_ref || github.ref_name }}

      - name: Cache pnpm modules and build
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            build/taro-docs
          key: ${{ runner.os }}-github
          restore-keys: |
            ${{ runner.os }}-

      - name: install
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm run build:github
